# Tensors for Beginners - Python Companion

The code in this notebook accompanies the YouTube video series `Tensors for Beginners`, published by user `eigenchris`, which can be found here:

https://www.youtube.com/playlist?list=PLJHszsWbB6hrkmmq57lX8BV-o-YIOFsiG

The notebook is organized by video, with material relevant for a certain video under the header corresponding to that video's title.

I found it helpful to play around with tensors in an interactive environment as I worked my way through the videos, and I think that it contributed to my understanding of the material.  I figured that I'd organize and publish my scratch work in case anybody else might find it helpful as a starting point - please hack it up!

Feel free to make additions and submit a pull request!

Thank you `eigenchris` for making such a valuable video series.  Both the instruction of specific topics and the overall logical flow of the series is very clear.

-Ben


In [15]:
from sympy import symbols, Array, tensorproduct
import numpy as np

# ------------------------------------------------------------------------------------------------
# Tensors for Beginners 11: Linear maps are Vector-Covector Pairs

Code for this video includes that which constructs a general linear map out basis vectors in R^2, and that which constructs a specific linear map out of basis vectors in R^2 and applies it to a vector.

## Constructing a linear map out of basis vectors and covectors in R^2

Here we use the standard R^2 basis vectors and covectors to construct a general linear map, represented by a 2x2 NumPy array.  We can index this array from Python just as is implied by it's Einstein notation representation, by it's dual index (L[x][y]).

In [3]:
# build basis vectors
e1 = np.array([[1], [0]])
e2 = np.array([[0], [1]])

# build basis covectors - represented by 1x2 arrays
eps1 = np.array([[1, 0]])
eps2 = np.array([[0, 1]])

e1eps1 = np.kron(e1, eps1)
e1eps2 = np.kron(e1, eps2)
e2eps1 = np.kron(e2, eps1)
e2eps2 = np.kron(e2, eps2)

a, b, c, d = symbols("a b c d")

L = a * e1eps1 + b * e1eps2 + c * e2eps1 + d * e2eps2

print(L)
print('\n')
print(L[0][0])

[[a b]
 [c d]]


a


## Apply a linear map to a vector using tensor multiplication

This is pretty trivial - we are essentially reproducing matrix multiplication rules using NumPy.tensordot and the right indices.

In [4]:
a = 4
b = 5
c = -1
d = 8

L_prime = a * e1eps1 + b * e1eps2 + c * e2eps1 + d * e2eps2

print(L_prime, '\n')
v = np.array([[2], [4]])
print(v, '\n')

print("Applying linear map to vector...")
res = np.tensordot(L_prime, v, ((1), (0)))

print(res)

[[ 4  5]
 [-1  8]] 

[[2]
 [4]] 

Applying linear map to vector...
[[28]
 [30]]


# ------------------------------------------------------------------------------------------------
# Tensors for Beginners 12: Bilinear forms are Covector-Covector pairs

Included in this section is code to compute a Kronecker product of general covectors in R^2 and apply it to a pair of general vectors, and code to compute a Kronecker product of two specific vectors in R^2 and apply it to a pair of specific vectors in R^2 - both one at a time, and after combining the two vectors into their own rank (2, 0) tensor.

## Computing a Kronecker product of two general covectors (in R^2)

Here we compute the Kronecker product of two covectors from R^2.

In [16]:
a1, a2, b1, b2 = symbols("a1 a2 b1 b2")

# build our general covectors
a = Array([a1, a2])
b = Array([b1, b2])

print("We've constructed two general covectors, which are represented by the following 1x2 arrays:")
print("a", a)
print("b", b)

print("Let's take the Kronecker product of these arrays:")
# Kronecker product of arrays
c = tensorproduct(a, b)
print(c)


We've constructed two general covectors, which are represented by the following 1x2 arrays:
a [a1, a2]
b [b1, b2]
Let's take the Kronecker product of these arrays:
[[a1*b1, a1*b2], [a2*b1, a2*b2]]


## (Example) Building a specific bilinear form out of two specific covectors (in R^2)

Here we construct coefficients for a specific bilinear form using sympy.tensorproduct.  A similar operation exists in NumPy as numpy.kron(), though it flattens the output matrix.

In [118]:
d = Array([1, 2])
e = Array([3, 4])

print("Covectors:")
print("d", d)
print("e", e)

# take the Kronecker product
bilin_form = tensorproduct(d, e)


print("Bilinear form - d (x) e:")
print(bilin_form)


Covectors:
d [1, 2]
e [3, 4]
Bilinear form - d (x) e:
[[3, 4], [6, 8]]


## Multiplying a general bilinear form by two vectors

Here we build a rank (0, 2) tensor out of two general covectors in R^2 and sequentially apply it to two general vectors in R^2, the result being a general scalar - a 0 rank tensor represented by a 1x1x1 dimensional array.

I'm doing tensor multiplication/application using NumPy's np.tensordot method, as the API for the equivalent operation in SymPy confused me a little (or at least the documentation did).


In [151]:
# Construct a general bilinear form
B11, B12, B21, B22 = symbols("B11 B12 B21 B22")
# this is represented by a row of rows, or a (1x2x2) NumPy array
print("Our bilinar form B, represented by a row of rows - in this case a (1x2x2) Numpy array:", '\n')
B = np.array([[[B11, B12], [B21, B22]]])
print(B, '\n')
print("Shape:", B.shape, '\n')

# construct two vectors
v1, v2, w1, w2 = symbols("v1 v2 w1 w2")
v = np.array([[v1], [v2]])
w = np.array([[w1], [w2]])

# multiply the bilinear form by the first vector
after_first_multiplication = np.tensordot(B, v, ((1), (0)))
print("Multiply B by the first vector V, we end up with a simple covector/row, represented by a (1x2x1) array:", '\n')
print(after_first_multiplication, '\n')
print("Shape:", after_first_multiplication.shape, '\n')

# multiply the resulting covector by the second vector
print("Multiply the resulting covector by the second vector, performing another contraction into a scalar - a (1x1x1 array):", '\n')
res = np.tensordot(after_first_multiplication, w, ((1), (0)))
print(res)
print("Shape:", res.shape)

Our bilinar form B, represented by a row of rows - in this case a (1x2x2) Numpy array: 

[[[B11 B12]
  [B21 B22]]] 

Shape: (1, 2, 2) 

Multiply B by the first vector V, we end up with a simple covector/row, represented by a (1x2x1) array: 

[[[B11*v1 + B21*v2]
  [B12*v1 + B22*v2]]] 

Shape: (1, 2, 1) 

Multiply the resulting covector by the second vector, performing another contraction into a scalar - a (1x1x1 array): 

[[[w1*(B11*v1 + B21*v2) + w2*(B12*v1 + B22*v2)]]]
Shape: (1, 1, 1)


## (Example) Multiplying a specific bilinear form by two vectors

In this cell we build a bilinear form out of covectors from R^2, then sequentially apply it to two R^2 vectors.  Then we combine the two vectors (rank (1, 0) tensors) we've built into new rank (2, 0) tensor using the Kronecker product, and apply the same bilinear form to that tensor, getting the same result - a (0, 0) rank tensor.


In [27]:
# Build a bilinear form

B = np.array([[[2, 3], [1, 4]]])
print("Our bilinar form B, represented by a row of rows - in this case a (1x2x2) Numpy array:", '\n')
print(B, '\n')
print("Shape:", B.shape, '\n')

# Build two vectors
v = np.array([[4], [5]])
w = np.array([[2], [3]])
print("Two vectors:")
print(v)
print('\n')
print(w)
print('\n')

# apply the bilinear form to the two vectors
print("Applying the bilinear form to the two vectors, one at a time:")
res_1 = np.tensordot(B, v, ((1), (0)))
print(res_1, '\n')
res_2 = np.tensordot(res_1, w, ((1), (0)))
print("Result...", '\n')
print(res_2, '\n')

print("now let's combine the two vectors into a rank (2, 0) tensor A and apply B to it")

# Kronecker product of v and w - we have to reshape the resulting array into the correct dimensions
# because NumPy flattens it in the output...
A = np.kron(v, w).reshape((2, 2, 1))
print("A - a rank (2, 0) tensor:")
print(A, '\n')
print(A.shape)

# doing the tensor application / contraction of B on A
print("Applying B to A...", '\n')
res_3 = np.tensordot(B, A, ((1, 2), (0, 1)))

print("Result...", '\n')
print(res_3)

# check that the results are the same - the kronecker product operation is the inverse of the tensor contraction
# operation
assert res_3 == res_2

Our bilinar form B, represented by a row of rows - in this case a (1x2x2) Numpy array: 

[[[2 3]
  [1 4]]] 

Shape: (1, 2, 2) 

Two vectors:
[[4]
 [5]]


[[2]
 [3]]


Applying the bilinear form to the two vectors, one at a time:
[[[13]
  [32]]] 

Result... 

[[[122]]] 

now let's combine the two vectors into a rank (2, 0) tensor A and apply B to it
A - a rank (2, 0) tensor:
[[[ 8]
  [12]]

 [[10]
  [15]]] 

(2, 2, 1)
Applying B to A... 

Result... 

[[122]]


# ------------------------------------------------------------------------------------------------
# Tensors for Beginners 14: Tensors are general vector/covector combinations

TODO explanation

## Constructing tensors D and Q, generally

Here we build representations of tensors D and Q using general arrays.  We'll build a complete basis for the spaces inhabited by D and Q using Kronecker products of our "building block" tensors - vectors and covectors, then multiply each basis element by some general coefficient

In [39]:
# TODO!

# build basis vectors
e1 = np.array([[1], [0]])
e2 = np.array([[0], [1]])

# build basis covectors - represented by 1x2 arrays
eps1 = np.array([[1, 0]])
eps2 = np.array([[0, 1]])

# take the
print("Let's slowly build D from scratch out of a pair of basis vectors...", '\n')
print("first we'll construct a basis for the space inhabited by D, by taking Kronecker products of possible combinations of basis vectors:", '\n')
# we have to reshape the arrays from np.kron to "de-flatten" them
# construct basis for vector space inhabited by D
b1 = np.kron(e1, e1).reshape((2, 2, 1))
b2 = np.kron(e1, e2).reshape((2, 2, 1))
b3 = np.kron(e2, e1).reshape((2, 2, 1))
b4 = np.kron(e2, e2).reshape((2, 2, 1))

print("here is our basis for ea (x) eb:", '\n')
print(b1, '\n', b2, '\n', b3, '\n', b4)

print("let's set some arbitrary coefficients and dot our coefficients and our basis...", '\n')
a, b, c, d = symbols("a b c d")
D11 = a
D12 = b
D21 = c
D22 = d

# build D out of our general coefficients
D = D11 * b1 + D12 * b2 + D21 * b3 + D22 * b4

print("Here is our general tensor D:", '\n')
print(D)

print("Now let's build a basis for the vector space inhabited by Q using the Kronecker product of our bases:", '\n')
b1Q = np.kron(e1, eps1)

print(b1Q)

## TODO: what is the array dimension?!?!


Let's slowly build D from scratch out of a pair of basis vectors... 

first we'll construct a basis for the space inhabited by D, by taking Kronecker products of possible combinations of basis vectors: 

here is our basis for ea (x) eb: 

[[[1]
  [0]]

 [[0]
  [0]]] 
 [[[0]
  [1]]

 [[0]
  [0]]] 
 [[[0]
  [0]]

 [[1]
  [0]]] 
 [[[0]
  [0]]

 [[0]
  [1]]]
let's set some arbitrary coefficients and dot our coefficients and our basis... 

Here is our general tensor D: 

[[[a]
  [b]]

 [[c]
  [d]]]
Now let's build a basis for the vector space inhabited by Q using the Kronecker product of our bases: 

[[1 0]
 [0 0]]


In [22]:
# todo change of basis

In [44]:
np.kron(b1Q, eps1)

array([[1, 0, 0, 0],
       [0, 0, 0, 0]])

In [45]:
np.kron(b1Q, eps1).shape

(2, 4)

In [47]:
# I think this is right
np.kron(b1Q, eps1).reshape((2, 2, 2))

array([[[1, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])