In [17]:
import numpy as np
from sympy import symbols

## Constructing a linear map out of basis vectors and covectors in R^2

Here we use the standard R^2 basis vectors and covectors to construct a general linear map, represented by a 2x2 NumPy array.  We can index this array from Python just as is implied by it's Einstein notation representation, by it's dual index (L[x][y]).

In [20]:
# build basis vectors
e1 = np.array([[1], [0]])
e2 = np.array([[0], [1]])

# build basis covectors - represented by 1x2 arrays
eps1 = np.array([[1, 0]])
eps2 = np.array([[0, 1]])

e1eps1 = np.kron(e1, eps1)
e1eps2 = np.kron(e1, eps2)
e2eps1 = np.kron(e2, eps1)
e2eps2 = np.kron(e2, eps2)

a, b, c, d = symbols("a b c d")

L = a * e1eps1 + b * e1eps2 + c * e2eps1 + d * e2eps2

print(L)
print('\n')
print(L[0][0])

[[a b]
 [c d]]


a


## Apply a linear map to a vector using tensor multiplication

This is pretty trivial - we are essentially reproducing matrix multiplication rules using NumPy.tensordot and the right indices.

In [25]:
a = 4
b = 5
c = -1
d = 8

L_prime = a * e1eps1 + b * e1eps2 + c * e2eps1 + d * e2eps2

print(L_prime, '\n')
v = np.array([[2], [4]])
print(v, '\n')

print("Applying linear map to vector...")
res = np.tensordot(L_prime, v, ((1), (0)))

print(res)

[[ 4  5]
 [-1  8]] 

[[2]
 [4]] 

Applying linear map to vector...
[[28]
 [30]]
